version: "3.9"

services:
    client:
        build: client
        ports:
            - 3000:3000
        env_file: client/.env
        depends_on:
            - server
    server:
        build: server
        ports:
            - 5000:5000
        env_file: server/.env
